### ISSUE TITLE
Error while doing make

### ISSUE THREAD

**Issue by alexstjean** [Ark444/YateBTS_smssend#1]
### log:

g++ -std=c++11 -fPIC  -I /usr/local/include/yate/ -c smssend.cpp  -o smssend.o
smssend.cpp: In static member function ‘static bool {anonymous}::SmsSendPlugin::sendSMS(const TelEngine::String&, const TelEngine::String&, const TelEngine::String&)’:
smssend.cpp:79:68: error: cannot pass objects of non-trivially-copyable type ‘const class TelEngine::String’ through ‘...’
    Debug(DebugGoOn, "Couldn't retrieve TMSI for MSISDN: %s", msisdn);
                                                                    ^
make: *** [smssend.o] Error 1

**Comment by trpyn** [comment]
Hi, I can't reproduce the error, it works fine for me, can you provide more details?
Wich version of yate did you install, and what's the version of your g++?

**Comment by alexstjean** [comment]
Yate 5.5.1 devel1 r and g++ 4.8.4

**Comment by trpyn** [comment]
Well, I've tried with g++ (Debian 4.9.2-10) 4.9.2 ; and I do get the error.
I recommand to upgrade your g++ to the latest version (I have no problem with g++ 6.2.1)

Please try and let me know if that fixes the issue :)

**Comment by alexstjean** [comment]
It fixed the issue! thanks a lot!

I'm going to send you an email on how to use it.
