### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by eliddell1** [Ark444/YateBTS_smssend#3]
I would like to see a way to send to all msisdn via comma separations or to all registered msisdn's via regex .* or something

**Comment by trpyn** [comment]
Hello,
first, please learn to say hi or hello when speaking to someone, I wanted to close this issue for only this reason.
Anyway, I don't have the bladeRF anymore, so I have no way to test this feature even if I add it. Feel free to make a fork of this repo or a pull request if you add it :D 

If you don't feel like adding this feature directly to the plugin, I may suggest you to make a script that connects to the telnet interface and get all the MSISDN and send a message for each of them. (ugly but it should work)

**Comment by eliddell1** [comment]
thank you and sorry, meant no offense by not saying hi.
Can you point to any documentation on how to writing a telnet command patch for yate?

**Comment by trpyn** [comment]
Sorry I've been a bit harsh, I had just woken up, was a bit grumpy ^^'
Well I'd probably do it using the pexpect package in python, it allows to manage i/o dynamically in a script. Or maybe in a bash script, but I'm not sure how complex it would be.
