### ISSUE TITLE
make install fails on raspian

### ISSUE THREAD

**Issue by eliddell1** [Ark444/YateBTS_smssend#4]
hello, I installed this fine on my normal linux box, but when i run the make files on a raspberry pi i get the following error:

root@pitower:/YateBTS_smssend# make && make install
g++ -std=c++11 -fPIC  -I /usr/local/include/yate/ -c smssend.cpp  -o smssend.o
smssend.cpp: In static member function ‘static bool {anonymous}::SmsSendPlugin::sendSMS(const TelEngine::String&, const TelEngine::String&, const TelEngine::String&)’:
smssend.cpp:79:68: error: cannot pass objects of non-trivially-copyable type ‘const class TelEngine::String’ through ‘...’
    Debug(DebugGoOn, "Couldn't retrieve TMSI for MSISDN: %s", msisdn);
                                                                    ^
Makefile:27: recipe for target 'smssend.o' failed

any ideas?

**Comment by trpyn** [comment]
Hi, it looks like the same error as #1 , try updating your g++ :)

**Comment by eliddell1** [comment]
looking into it.. thanks!

**Comment by eliddell1** [comment]
updated to gcc6 and still get the same error

**Comment by eliddell1** [comment]
i think i got it.. the pi definately needed to update gcc to v 6, which had to be done via stretch repository instead of the jessie repository.
I hadn't realized that the old gcc was still default, so i had to modify the makefile to point to g++-6 instead of just g++
