### ISSUE TITLE
SUggestion ....

### ISSUE THREAD

**Issue by gronget** [Ark444/YateBTS_smssend#7]
could you please implement a senario where the sender can be in letter case.....for example a name 
otherwise it works just fine..
iam gonna try PDU.... dont know if it can

**Comment by gronget** [comment]
What are the basics of writing plugins for yate.... i plan writing one

**Comment by trpyn** [comment]
Hello to you too,
The sender is just a string, so you should be able to send a name already. 

For the basics, read the doc, here are the two main wiki about it: 
http://docs.yate.ro/wiki/Main_Page 
https://wiki.yatebts.com/index.php/Main_Page

**Comment by gronget** [comment]
Hey
I can send message in TPDU format

**Comment by gronget** [comment]
Sorry. I meant to ask if it's possible to send TPDU massage format

**Comment by trpyn** [comment]
Sorry, I have no idea if it is possible or not...
